### ISSUE TITLE
Weird Error: Failed resolution of: Landroid/arch/lifecycle/LifecycleObserver;

### ISSUE THREAD

**Issue by randy-johnson** [Yermo/nativescript-mapbox#200]
I am running NS 3.4.2

with mapbox 3.3.0

I am getting this error when going to my map page.  This just started recently. I noticed it when on 3.4.1.

I cannot figure out what is causing the error.

I commented out my code that adds the markers.  I am just trying to show the map.

I have removed and added the android platform as well as deleting node_modules.

Any ideas on what the issue could be?

Thank You

```
JS: Mapbox onMapReady for Android, native object received: com.mapbox.mapboxsdk.maps.MapView{7f513c VFED..CL. ........ 0,0-1440,2256}
02-04 23:01:00.582 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[]) (Runtime.java:-2)
02-04 23:01:00.582 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.dispatchCallJSMethodNative(int, java.lang.String, boolean, long, java.lang.Class, java.lang.Object[]) (Runtime.java:1088)
02-04 23:01:00.582 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long,java.lang.Object[]) (Runtime.java:970)
02-04 23:01:00.582 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:957)
02-04 23:01:00.582 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, java.lang.Object[]) (Runtime.java:941)
02-04 23:01:00.582 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, java.lang.Object[]) (Runtime.java:933)
02-04 23:01:00.582 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[]) (Runtime.java:-2)
02-04 23:01:00.582 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.dispatchCallJSMethodNative(int, java.lang.String, boolean, long, java.lang.Class, java.lang.Object[]) (Runtime.java:1088)
02-04 23:01:00.582 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long,java.lang.Object[]) (Runtime.java:970)
02-04 23:01:00.582 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:957)
02-04 23:01:00.582 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, java.lang.Object[]) (Runtime.java:941)
02-04 23:01:00.582 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, java.lang.Object[]) (Runtime.java:933)
02-04 23:01:00.583 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[]) (Runtime.java:-2)
02-04 23:01:00.583 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.dispatchCallJSMethodNative(int, java.lang.String, boolean, long, java.lang.Class, java.lang.Object[]) (Runtime.java:1088)
02-04 23:01:00.583 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long,java.lang.Object[]) (Runtime.java:970)
02-04 23:01:00.583 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:957)
02-04 23:01:00.583 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, java.lang.Object[]) (Runtime.java:941)
02-04 23:01:00.583 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, java.lang.Object[]) (Runtime.java:933)
02-04 23:01:00.583 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodNative(int, int, java.lang.String, int, boolean, java.lang.Object[]) (Runtime.java:-2)
02-04 23:01:00.583 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.dispatchCallJSMethodNative(int, java.lang.String, boolean, long, java.lang.Class, java.lang.Object[]) (Runtime.java:1088)
02-04 23:01:00.583 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethodImpl(java.lang.Object, java.lang.String, java.lang.Class, boolean, long,java.lang.Object[]) (Runtime.java:970)
02-04 23:01:00.583 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, long, java.lang.Object[]) (Runtime.java:957)
02-04 23:01:00.583 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, boolean, java.lang.Object[]) (Runtime.java:941)
02-04 23:01:00.583 30506 30506 I art     :   at java.lang.Object com.tns.Runtime.callJSMethod(java.lang.Object, java.lang.String, java.lang.Class, java.lang.Object[]) (Runtime.java:933)
System.err: com.tns.NativeScriptException:
System.err: Calling js method run failed
System.err:
System.err: Error: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/arch/lifecycle/LifecycleObserver;
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
System.err:     android.os.Handler.handleCallback(Handler.java:751)
System.err:     android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     android.os.Looper.loop(Looper.java:154)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6077)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.LifecycleObserver" on path: DexPathList[[zip file "/data/app/com.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp-1/lib/x86, /data/app/com.myapp-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
System.err:     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:380)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
System.err:     android.os.Handler.handleCallback(Handler.java:751)
System.err:     android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     android.os.Looper.loop(Looper.java:154)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6077)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
System.err: File: "file:///data/data/com.myapp/files/app/tns_modules/nativescript-mapbox/mapbox.js, line: 145, column: 30
System.err:
System.err: StackTrace:
System.err:     Frame: function:'_showLocation', file:'file:///data/data/com.myapp/files/app/tns_modules/nativescript-mapbox/mapbox.js', line: 145,column: 31
System.err:     Frame: function:'', file:'file:///data/data/com.myapp/files/app/tns_modules/nativescript-mapbox/mapbox.js', line: 51, column: 37
System.err:     Frame: function:'invoke', file:'file:///data/data/com.myapp/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
System.err:     Frame: function:'run', file:'file:///data/data/com.myapp/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
System.err:     at android.os.Handler.handleCallback(Handler.java:751)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
System.err: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/arch/lifecycle/LifecycleObserver;
System.err:     ... 14 more
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.LifecycleObserver" on path: DexPathList[[zip file "/data/app/com.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp-1/lib/x86, /data/app/com.myapp-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     ... 14 more
JS: DEBUG app/app.js ERROR! +23576
JS: DEBUG app/app.js ERROR! Error The application crashed because of an uncaught exception. You can look at "stackTrace" or "nativeException" for more detailed information about the exception. An uncaught Exception occurred on "main" thread.
JS: com.tns.NativeScriptException:
JS: Calling js method run failed
JS:
JS: Error: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/arch/lifecycle/LifecycleObserver;
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
JS:     android.os.Handler.handleCallback(Handler.java:751)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:154)
JS:     android.app.ActivityThread.main(ActivityThread.java:6077)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
JS: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.LifecycleObserver" on path: DexPathList[[zip file "/data/app/com.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp-1/lib/x86, /data/app/com.myapp-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
JS:     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
JS:     java.lang.ClassLoader.loadClass(ClassLoader.java:380)
JS:     java.lang.ClassLoader.loadClass(ClassLoader.java:312)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
JS:     android.os.Handler.handleCallback(Handler.java:751)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:154)
JS:     android.app.ActivityThread.main(ActivityThread.java:6077)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
JS: File: "file:///data/data/com.myapp/files/app/tns_modules/nativescript-mapbox/mapbox.js, line: 145, column: 30
JS:
JS: StackTrace:
JS:     Frame: function:'_showLocation', file:'file:///data/data/com.myapp/files/app/tns_modules/nativescript-mapbox/mapbox.js', line: 145, column:31
JS:     Frame: function:'', file:'file:///data/data/com.myapp/files/app/tns_modules/nativescript-mapbox/mapbox.js', line: 51, column: 37
JS:     Frame: function:'invoke', file:'file:///data/data/com.myapp/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
JS:     Frame: function:'run', file:'file:///data/data/com.myapp/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13
JS:
JS:
JS:     at com.tns.Runtime.callJSMethodNative(Native Method)
JS:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
JS:     at android.os.Handler.handleCallback(Handler.java:751)
JS:     at android.os.Handler.dispatchMessage(Handler.java:95)
JS:     at android.os.Looper.loop(Looper.java:154)
JS:     at android.app.ActivityThread.main(ActivityThread.java:6077)
JS:     at java.lang.reflect.Method.invoke(Native Method)
JS:     at com.android.internal.os.Zygo
JS: teInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
JS:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
JS: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/arch/lifecycle/LifecycleObserver;
JS:     ... 14 more
JS: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.LifecycleObserver" on path: DexPathList[[zip file "/data/app/com.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp-1/lib/x86, /data/app/com.myapp-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
JS:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
JS:     at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
JS:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
JS:     ... 14 more
JS:  {} +0
```
Here is my xml code.  Unchanged in quite awhile. 
```
<map:MapboxView
                accessToken=""
                mapStyle="streets"
                latitude="{{ mapModel.latitude }}"
                longitude="{{ mapModel.longitude }}"
                zoomLevel="{{ mapModel.zoom }}"
                showUserLocation="true"
                mapReady="onMapReady"
                delay="1000"
                bearing="{{ mapModel.bearing }}" 
                tilt="{{ mapModel.tilt }}" 
                i-padding="50,50,50,50" 
                padding="{{ mapModel.padding }}" 
                mapReady="onMapReady" 
                markerSelect="onMarkerSelect" 
                cameraChanged="onCameraChanged" 
                markerInfoWindowTapped="onInfoWindowSelect" 
                height="100%" width="100%"
                >
                <!-- -->
            </map:MapboxView>
```

**Comment by randy-johnson** [comment]
Any suggestions?

**Comment by randy-johnson** [comment]
I had to put this in my app.gradle.

```
compile ('android.arch.lifecycle:livedata:1.1.0') {
        force = true;
    }
    compile ('android.arch.lifecycle:viewmodel:1.1.0') {
        force = true;
    }
```

Not sure why though, but this worked.  A big thanks to Pete.K on the NS forum.
