### ISSUE TITLE
TypeError: Cannot read property 'getInstance' of undefined

### ISSUE THREAD

**Issue by murat199** [Yermo/nativescript-mapbox#218]
Hello  I get that error when I create a new project with tns create command and add xml definition mapbox. 
I tried it with nativescript 3.4.0 and now 4.0.0 results are same.

An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method run failed

TypeError: Cannot read property 'getInstance' of undefined
File: "file:///data/data/org.nativescript.MapXX/files/app/tns_modules/nativescript-mapbox/mapbox.js, line: 39, column: 39

StackTrace: 
	Frame: function:'MapboxView.initMap', file:'file:///data/data/org.nativescript.MapXX/files/app/tns_modules/nativescript-mapbox/mapbox.js', line: 39, column: 40
	Frame: function:'', file:'file:///data/data/org.nativescript.MapXX/files/app/tns_modules/nativescript-mapbox/mapbox.js', line: 30, column: 19
	Frame: function:'invoke', file:'file:///data/data/org.nativescript.MapXX/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
	Frame: function:'run', file:'file:///data/data/org.nativescript.MapXX/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by EddyVerbruggen** [comment]
Without a demo repo it's hard to figure out. Note that I'm about to release version 4.0.0 with an updated demo ap, so please give that a spin before reopening.

**Comment by slasho** [comment]
I'm facing same problem here on 4.0.1

any idea?

**Comment by murat199** [comment]
I have a idea. I had the same problem and i solved the my problem. 
My Nativescript project's version is 4.0.1. (you can check this on package.json file)

tns plugin add nativescript-mapbox@4.0.0

`<ContentView height="240" width="240">
                
                <map:MapboxView
                    accessToken="your_token"
                    mapStyle="traffic_night"
                    latitude="52.3702160"
                    longitude="4.8951680"
                    zoomLevel="3"
                    showUserLocation="true">
                </map:MapboxView>
            </ContentView>  `

then 
tns platform remove android
then
tns platform add android
then
tns run android
