### ISSUE TITLE
vue js native doesn't work

### ISSUE THREAD

**Issue by promistrio** [Yermo/nativescript-mapbox#244]
I got this error

> An uncaught Exception occurred on "main" thread.
> java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.application/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
> Calling js method onCreate failed
> 
> TypeError: Could not load view for: mapbox. Error: com.tns.NativeScriptException: Failed to find module: "nativescript-mapbox/mapbox.common", relative to: app/tns_modules/
>     com.tns.Module.resolvePathHelper(Module.java:146)
>     com.tns.Module.resolvePath(Module.java:55)
>     com.tns.Runtime.callJSMethodNative(Native Method)
>     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
>     com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
>     com.tns.Runtime.callJSMethod(Runtime.java:970)
>     com.tns.Runtime.callJSMethod(Runtime.java:954)
>     com.tns.Runtime.callJSMethod(Runtime.java:946)
>     com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
>     android.app.Activity.performCreate(Activity.java:6912)
>     android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
>     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2824)
>     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2946)
>     android.app.ActivityThread.-wrap12(ActivityThread.java)
>     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1634)
>     android.os.Handler.dispatchMessage(Handler.java:113)
>     android.os.Looper.loop(Looper.java:205)
>     android.app.ActivityThread.main(ActivityThread.java:6783)
>     java.lang.reflect.Method.invoke(Native Method)
>     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
>     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1086)
> File: "file:///data/data/org.nativescript.application/files/app/app.js, line: 2307, column: 6
> 
> StackTrace: 
> 	Frame: function:'getViewClass', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 5063, column: 11
> 	Frame: function:'ElementNode', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 5986, column: 21
> 	Frame: function:'createElement', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 6084, column: 12
> 	Frame: function:'createElement', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 6194, column: 23
> 	Frame: function:'createElm', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3566, column: 19
> 	Frame: function:'createChildren', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3669, column: 9
> 	Frame: function:'createElm', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3571, column: 9
> 	Frame: function:'createChildren', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3669, column: 9
> 	Frame: function:'createElm', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3571, column: 9
> 	Frame: function:'patch', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 4078, column: 7
> 	Frame: function:'Vue._update', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3129, column: 19
> 	Frame: function:'updateComponent', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3257, column: 10
> 	Frame: function:'get', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 2302, column: 25
> 	Frame: function:'Watcher', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 2291, column: 12
> 	Frame: function:'mountComponent', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3264, column: 3
> 	Frame: function:'mount', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 11358, column: 5
> 	Frame: function:'Vue.$mount', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 11386, column: 16
> 	Frame: function:'init', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 9826, column: 13
> 	Frame: function:'createComponent', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3595, column: 9
> 	Frame: function:'createElm', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3543, column: 9
> 	Frame: function:'patch', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 4117, column: 9
> 	Frame: function:'Vue._update', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3129, column: 19
> 	Frame: function:'updateComponent', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3257, column: 10
> 	Frame: function:'get', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 2302, column: 25
> 	Frame: function:'Watcher', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 2291, column: 12
> 	Frame: function:'mountComponent', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3264, column: 3
> 	Frame: function:'create', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 11343, column: 9
> 	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 51, column: 22
> 	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 101, column: 16
> 	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
> 	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
> 	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
> 
> 
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2871)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2946)
> 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1634)
> 	at android.os.Handler.dispatchMessage(Handler.java:113)
> 	at android.os.Looper.loop(Looper.java:205)
> 	at android.app.ActivityThread.main(ActivityThread.java:6783)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1086)
> Caused by: com.tns.NativeScriptException: 
> Calling js method onCreate failed
> 
> TypeError: Could not load view for: mapbox. Error: com.tns.NativeScriptException: Failed to find module: "nativescript-mapbox/mapbox.common", relative to: app/tns_modules/
>     com.tns.Module.resolvePathHelper(Module.java:146)
>     com.tns.Module.resolvePath(Module.java:55)
>     com.tns.Runtime.callJSMethodNative(Native Method)
>     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
>     com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
>     com.tns.Runtime.callJSMethod(Runtime.java:970)
>     com.tns.Runtime.callJSMethod(Runtime.java:954)
>     com.tns.Runtime.callJSMethod(Runtime.java:946)
>     com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
>     android.app.Activity.performCreate(Activity.java:6912)
>     android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
>     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2824)
>     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2946)
>     android.app.ActivityThread.-wrap12(ActivityThread.java)
>     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1634)
>     android.os.Handler.dispatchMessage(Handler.java:113)
>     android.os.Looper.loop(Looper.java:205)
>     android.app.ActivityThread.main(ActivityThread.java:6783)
>     java.lang.reflect.Method.invoke(Native Method)
>     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
>     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1086)
> File: "file:///data/data/org.nativescript.application/files/app/app.js, line: 2307, column: 6
> 
> StackTrace: 
> 	Frame: function:'getViewClass', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 5063, column: 11
> 	Frame: function:'ElementNode', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 5986, column: 21
> 	Frame: function:'createElement', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 6084, column: 12
> 	Frame: function:'createElement', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 6194, column: 23
> 	Frame: function:'createElm', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3566, column: 19
> 	Frame: function:'createChildren', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3669, column: 9
> 	Frame: function:'createElm', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3571, column: 9
> 	Frame: function:'createChildren', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3669, column: 9
> 	Frame: function:'createElm', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3571, column: 9
> 	Frame: function:'patch', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 4078, column: 7
> 	Frame: function:'Vue._update', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3129, column: 19
> 	Frame: function:'updateComponent', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3257, column: 10
> 	Frame: function:'get', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 2302, column: 25
> 	Frame: function:'Watcher', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 2291, column: 12
> 	Frame: function:'mountComponent', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3264, column: 3
> 	Frame: function:'mount', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 11358, column: 5
> 	Frame: function:'Vue.$mount', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 11386, column: 16
> 	Frame: function:'init', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 9826, column: 13
> 	Frame: function:'createComponent', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3595, column: 9
> 	Frame: function:'createElm', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3543, column: 9
> 	Frame: function:'patch', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 4117, column: 9
> 	Frame: function:'Vue._update', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3129, column: 19
> 	Frame: function:'updateComponent', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3257, column: 10
> 	Frame: function:'get', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 2302, column: 25
> 	Frame: function:'Watcher', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 2291, column: 12
> 	Frame: function:'mountComponent', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 3264, column: 3
> 	Frame: function:'create', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 11343, column: 9
> 	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 51, column: 22
> 	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 101, column: 16
> 	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
> 	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
> 	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
> 

Code:
`git clone https://vladosed@bitbucket.org/vladosed/mapbox-error-vue.js.git`

**Comment by promistrio** [comment]
after "npm install"
`npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mapbox-project@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
`

**Comment by EddyVerbruggen** [comment]
I cloned you repo and `npm run debug:ios` gave me this on the first try:

<img width="966" alt="screenshot 2018-08-13 at 20 26 02" src="https://user-images.githubusercontent.com/1426370/44050414-28ef6a3a-9f37-11e8-8f3b-6382fb20861c.png">

**Comment by promistrio** [comment]
I also try it in another computer and it work. If you have the same problem just remove dist and node_modules in you project and run npm install
