### ISSUE TITLE
Unable to create service com.mapbox.android.telemetry.TelemetryService: java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission

### ISSUE THREAD

**Issue by tarakinsuide** [Yermo/nativescript-mapbox#250]
Hi,

I'm installing native Android SDK and keep getting this error which is crashing my app. What's wrong?

 ```
  --------- beginning of crash
08-15 22:37:42.126 20794-20794/com.insuide.tarak.gitex20181 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.insuide.tarak.gitex20181, PID: 20794
    java.lang.RuntimeException: Unable to create service com.mapbox.android.telemetry.TelemetryService: java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3363)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1689)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:172)
        at android.app.ActivityThread.main(ActivityThread.java:6590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
        at android.os.Parcel.readException(Parcel.java:2005)
        at android.os.Parcel.readException(Parcel.java:1951)
        at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:691)
        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:900)
        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:471)
        at com.mapbox.android.core.location.AndroidLocationEngine.requestLocationUpdates(AndroidLocationEngine.java:103)
        at com.mapbox.android.telemetry.TelemetryService.onConnected(TelemetryService.java:94)
        at com.mapbox.android.core.location.AndroidLocationEngine.activate(AndroidLocationEngine.java:75)
        at com.mapbox.android.telemetry.TelemetryService.activateLocationEngine(TelemetryService.java:186)
        at com.mapbox.android.telemetry.TelemetryService.connectLocationEngine(TelemetryService.java:173)
        at com.mapbox.android.telemetry.TelemetryService.registerLocationReceiver(TelemetryService.java:164)
        at com.mapbox.android.telemetry.TelemetryService.createLocationReceiver(TelemetryService.java:160)
        at com.mapbox.android.telemetry.TelemetryService.onCreate(TelemetryService.java:41)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3353)
        at android.app.ActivityThread.-wrap4(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1689) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:172) 
        at android.app.ActivityThread.main(ActivityThread.java:6590) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
08-15 22:37:44.029 20794-20799/com.insuide.tarak.gitex20181 I/zygote64: Do partial code cache collection, code=29KB, data=19KB
    After code cache collection, code=29KB, data=19KB
    Increasing code cache capacity to 128KB
```

**Comment by dinodujmovic** [comment]
Maybe ?
https://github.com/EddyVerbruggen/nativescript-mapbox#installation

On Android the plugin adds this to the <application> node of app/App_Resources/Android/AndroidManifest.xml (the plugin already attempts to do so):

`<service android:name="com.mapbox.services.android.telemetry.service.TelemetryService" />`


If you get an error related to TelemetryService then please check it's there.

**Comment by bradmartin** [comment]
Same issue after some local build changes for different dependencies, can confirm adding the telemetryService to the manifest will get past it 👍

**Comment by bradmartin** [comment]
K circling back after fighting this for a couple hours. This can actually be related to play-services version.

I've been fighting a project with Kinvey & geolocation plugin which needs google play services. So I ended up with this in the app.gradle:

```
// Add your native dependencies here:
dependencies {
  compile "com.google.android.gms:play-services-location:12.0.1"
}

repositories {
  google() // Google's Maven repository
}

android {    
  defaultConfig {  
    generatedDensities = []
    applicationId = "com.permobil.smarteval"  
    minSdkVersion 21
    targetSdkVersion 28
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }
  project.ext {
    googlePlayServicesVersion = "12.0.1"
    firebaseMessagingVersion = "12.0.1"
    supportVersion = "28.+"
  }
} 
``` 

and now the mapbox telemetry error is gone. The real fix here in my case I am 99% certain was making sure the play-services library is pulled in my build as I am having to run a forked version of the plugin for gradle conflicts I have not resolved.

**Comment by kklimczak** [comment]
I noticed the same error when I used nativescript-bluetooth plugin. When I do any action connected with Bluetooth (e.g. requestPermission) this error appears on the screen. In my manifest exists entry of TelemetryService.
