### ISSUE TITLE
Cannot read property 'getInstance' of undefined

### ISSUE THREAD

**Issue by robertbruno** [Yermo/nativescript-mapbox#273]
I have a problem to instantiate mapbox nativescript plugin. I had followed the instructions but the problem persist.

* **XML**
```xml
<Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:map="nativescript-mapbox" navigatingTo="navigatingTo">

<StackLayout>
  <ActionBar title="{{ 'map' | translate }}" class="action-bar" [isUserInteractionEnabled]="isBusy">
      <NavigationButton text="{{ 'back' | translate }}" android.systemIcon="ic_menu_back" (tap)="back(isBusy)"></NavigationButton>
  </ActionBar>
  
  <StackLayout>
    <Label text="Nice map, huh!" class="title"></Label>
    <ContentView height="100%" width="100%">
      <MapboxView
          accessToken="my token"
          mapStyle="streets"
          latitude="50.467735"
          longitude="13.427718"
          hideCompass="true"
          zoomLevel="18"
          showUserLocation="false"
          disableZoom="false"
          disableRotation="false"
          disableScroll="false"
          disableTilt="false"
          (mapReady)="onMapReady($event)">
    </MapboxView>

    </ContentView>
  </StackLayout>

</StackLayout>
</Page>
```

* **Component**
```typescript
import { Component, OnInit } from '@angular/core';
import { BaseComponent } from "../base/base.component";
import { Router } from '@angular/router';
import { TranslateService } from 'ng2-translate';
import { RouterExtensions } from 'nativescript-angular/router';

@Component({
  moduleId: module.id,
  selector: 'app-map',
  templateUrl: './map.component.html',
  styleUrls: ['./map.component.scss']
})

export class MapComponent extends BaseComponent implements OnInit {

  constructor( 
    translate: TranslateService,
    router: Router,
    routerExtensions: RouterExtensions
  ) {
    super(routerExtensions, translate, router, null, null);
  }

  ngOnInit() { }

  onMapReady(event){
      console.log(event);
  }
}
```

> I registred the element on the app.moule.ts

```typescript
import { registerElement } from 'nativescript-angular/element-registry';
registerElement("MapboxView", () => require("nativescript-mapbox").MapboxView);
```

* **Error**
```bash
System.err: com.tns.NativeScriptException: 
System.err: Calling js method run failed
System.err: 
System.err: TypeError: Cannot read property 'getInstance' of undefined
System.err: File: "file:///data/data/org.nativescript.yanomappMobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js, line: 142, column: 24
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'MapboxView.initMap', file:'file:///data/data/org.nativescript.yanomappMobile/files/app/tns_modules/nativescript-mapbox/mapbox.js', line: 45, column: 41
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.yanomappMobile/files/app/tns_modules/nativescript-mapbox/mapbox.js', line: 31, column: 19
System.err: 	Frame: function:'ZoneDelegate.invokeTask', file:'file:///data/data/org.nativescript.yanomappMobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 398, column: 31
System.err: 	Frame: function:'Zone.runTask', file:'file:///data/data/org.nativescript.yanomappMobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 165, column: 47
System.err: 	Frame: function:'ZoneTask.invoke', file:'file:///data/data/org.nativescript.yanomappMobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 460, column: 38
System.err: 	Frame: function:'timer', file:'file:///data/data/org.nativescript.yanomappMobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1636, column: 29
System.err: 	Frame: function:'invoke', file:'file:///data/data/org.nativescript.yanomappMobile/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
System.err: 	Frame: function:'ZoneDelegate.invoke', file:'file:///data/data/org.nativescript.yanomappMobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 365, column: 26
System.err: 	Frame: function:'Zone.runGuarded', file:'file:///data/data/org.nativescript.yanomappMobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 138, column: 47
System.err: 	Frame: function:'', file:'file:///data/data/org.nativescript.yanomappMobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 116, column: 29
System.err: 	Frame: function:'run', file:'file:///data/data/org.nativescript.yanomappMobile/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:954)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err: 	at com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
System.err: 	at android.os.Handler.handleCallback(Handler.java:790)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
System.err: 	at android.os.Looper.loop(Looper.java:164)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6543)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
```

**Comment by robertbruno** [comment]
Sorry I did not realize that there was already a related issue
* [ssues/220](https://github.com/EddyVerbruggen/nativescript-mapbox/issues/220)

I remove and add android platform.
