### ISSUE TITLE
setOnMapClickListener / setOnMapLongClickListener makes the app crash

### ISSUE THREAD

**Issue by CSVerbeek** [Yermo/nativescript-mapbox#366]
Maybe I'm doing something wrong, but when I use setOnMapClickListener or setOnMapLongClickListener the app crashes on those events. I'm using Vue with typescript and passing in a `(data: LatLng) => void` listener. I also tried `() => void` and '(data: any) => void` as listeners.

I registered my Element in main.ts with
```Vue.registerElement("Mapbox", () => require("nativescript-mapbox").MapboxView );```

I use the component like so:
```
<Mapbox
        accessToken="<my-token>"
        mapStyle="traffic_day"
        latitude="52.092876"
        longitude="5.104480"
        hideCompass="true"
        zoomLevel="13"
        showUserLocation="false"
        disableZoom="false"
        disableRotation="true"
        disableScroll="false"
        disableTilt="true"
        @mapReady="onMapReady($event)"
></Mapbox>
```

And my `onMapReady` function:
```
onMapReady(args) {
        let map: MapboxView = args.map;

        map.setOnMapClickListener( ( point: LatLng ) => { console.log(point); } )
            .then( () => {
                console.log( "OnMapClick set" );
            } );

        // Placing the marker works perfectly
        map.addMarkers([
            {
                lat: 52.092876,
                lng: 5.104480,
                title: "Title",
                subtitle: "Subtitle",
                onTap: () => {
                    console.log("Marker tapped ");
                }
            }
        ]);
    }
```

So far it works and the app is running and showing the map as expected. When I click on the map however, the app crashes.
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
System.err: 
System.err: StackTrace:
System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
System.err:     at com.tns.gen.com.mapbox.mapboxsdk.maps.MapboxMap_OnMapClickListener.onMapClick(MapboxMap_OnMapClickListener.java:19)
System.err:     at com.mapbox.mapboxsdk.maps.MapGestureDetector.notifyOnMapClickListeners(MapGestureDetector.java:983)
System.err:     at com.mapbox.mapboxsdk.maps.MapGestureDetector$StandardGestureListener.onSingleTapConfirmed(MapGestureDetector.java:358)
System.err:     at com.mapbox.android.gestures.StandardGestureDetector$1.onSingleTapConfirmed(StandardGestureDetector.java:81)
System.err:     at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

Hopefully you can help. Thanks in advance.

**Comment by PhilippS93** [comment]
Hi,

you have to return `true `or `false` on Android for the `setOnMapClickListener `callback.


Best,
Philipp

**Comment by CSVerbeek** [comment]
Thanks @PhilippS93 ! That did the trick.
