### ISSUE TITLE
Exception on Android with Mapbox in XML

### ISSUE THREAD

**Issue by nraboy** [Yermo/nativescript-mapbox#62]
Hey,

I'm running into the following error:

```
JS: EXCEPTION: java.lang.NullPointerException: Attempt to read from field 'com.mapbox.mapboxsdk.geometry.LatLng com.mapbox.mapboxsdk.camera.CameraPosition.target' on a null object reference
JS:     com.mapbox.mapboxsdk.camera.CameraUpdateFactory$CameraPositionUpdate.getCameraPosition(CameraUpdateFactory.java:190)
JS:     com.mapbox.mapboxsdk.maps.MapboxMap.moveCamera(MapboxMap.java:278)
JS:     com.mapbox.mapboxsdk.maps.MapboxMap.moveCamera(MapboxMap.java:266)
JS:     com.mapbox.mapboxsdk.maps.MapView.setInitialState(MapView.java:260)
JS:     com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:247)
JS:     com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:182)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:895)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:879)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:871)
JS:     com.tns.gen.java.lang.Runnable.run(java.lang.Runnable.java)
JS:     android.os.Handler.handleCallback(Handler.java:739)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:135)
JS:     android.app.ActivityThread.main(ActivityThread.java:5254)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:372)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
JS: ORIGINAL STACKTRACE:
JS: Error: java.lang.NullPointerException: Attempt to read from field 'com.mapbox.mapboxsdk.geometry.LatLng com.mapbox.mapboxsdk.camera.CameraPosition.target' on a null object reference
JS:     com.mapbox.mapboxsdk.camera.CameraUpdateFactory$CameraPositionUpdate.getCameraPosition(CameraUpdateFactory.java:190)
JS:     com.mapbox.mapboxsdk.maps.MapboxMap.moveCamera(MapboxMap.java:278)
JS:     com.mapbox.mapboxsdk.maps.MapboxMap.moveCamera(MapboxMap.java:266)
JS:     com.mapbox.mapboxsdk.maps.MapView.setInitialState(MapView.java:260)
JS:     com.mapbox.mapboxsdk.maps.MapView.initialize(MapView.java:247)
JS:     com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:182)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:895)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:879)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:871)
JS:     com.tns.gen.java.lang.Runnable.run(java.lang.Runnable.java)
JS:     android.os.Handler.handleCallback(Handler.java:739)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:135)
JS:     android.app.ActivityThread.main(ActivityThread.java:5254)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:372)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
JS:     at Error (native)
JS:     at drawMap (/data/data/org.nativescript.nativescriptinstagram/files/app/tns_modules/nativescript-mapbox/mapbox.js:44:24)
JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.nativescriptinstagram/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:223:37)
JS:     at Object.onInvokeTask (/data/data/org.nativescript.nativescriptinstagram/files/app/tns_modules/@angular/core/bundles/core.umd.js:6197:41)
JS:     at ZoneDelegate.invokeTask (/data/data/org.nativescript.nativescriptinstagram/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:222:42)
JS:     at Zone.runTask (/data/data/org.nativescript.nativescriptinstagram/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:123:47)
JS:     at ZoneTask.invoke (/data/data/org.nativescript.nativescriptinstagram/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:291:33)
JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.nativescriptinstagram/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:190:28)
JS:     at Object.onInvoke (/data/data/org.nativescript.nativescriptinstagram/files/app/tns_modules/@angular/core/bundles/core.umd.js:6206:41)
JS:     at ZoneDelegate.invoke (/data/data/org.nativescript.nativescriptinstagram/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:189:34)
```

It works fine on iOS, but not Android.  I've tried Android 4.4.4 and Android 5.0.1 without any luck.  The application is using NativeScript 2.4 with Angular and the Mapbox is declared via the XML.

Any ideas?

Thanks,

**Comment by nraboy** [comment]
For your reference, my project is here:

https://github.com/nraboy/nativescript-photos-near-me

**Comment by EddyVerbruggen** [comment]
Thanks for the demo project. The problem seems to be that in the XML definition an initial `latitude` and `longitude` property is required. I'll change that and see if I hit other issues as well with your demo.

**Comment by EddyVerbruggen** [comment]
Check https://github.com/nraboy/nativescript-photos-near-me/pull/1
