### ISSUE TITLE
Unable to start activity ComponentInfo{org.nativescript.mapboxdemo/com.tns.NativeScriptActivity}

### ISSUE THREAD

**Issue by prodigy7** [Yermo/nativescript-mapbox#7]
NativeScript: 1.6.2

Today I have checkout your current mapbox demo but I'cant get it running on my system. I get this error (only a part of fully error text, couldn't copy it all).

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.mapboxdemo/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'widgets' of undefined
File: "/data/data/org.nativescript.mapboxdemo/files/app/tns_modules/ui/frame/frame.js, line: 327, column: 39

StackTrace: 
    Frame: function:'NativeActivity.onCreate', file:'/data/data/org.nativescript.mapboxdemo/files/app/tns_modules/ui/frame/frame.js', line: 327, column: 40


    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native M[...]
```

Generally I have amount of experience in software development, but I'm new to nativescript. Maybe is a really simple fault and I don't recognize it ...

**Comment by EddyVerbruggen** [comment]
Hi, I just updated my NativeScript to 1.7.0 and checked this plugin. Updated the iOS podpec while I was at it (newer native Mapbox SDK) and fixed an error with Android `setTilt`. All seems fine, so please update your NativeScript and try again.

**Comment by prodigy7** [comment]
Ok, new checkout ... some new errors. What could be wrong?
```
Executing before-prepare hook from /home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 1.8.7
app/examples/example-base-page.ts(13,31): error TS2306: File '/home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/node_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.d.ts' is not a module.
app/examples/example-base-page.ts(13,31): error TS2656: Exported external package typings file '/home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/node_modules/nativescript-telerik-ui/sidedrawer/sidedrawer.d.ts' is not a module. Please contact the package author to update the package definition.
app/examples/listview/layouts/listview-layouts.ts(2,33): error TS2306: File '/home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/node_modules/nativescript-telerik-ui/listview/listview.d.ts' is not a module.
app/examples/listview/layouts/listview-layouts.ts(2,33): error TS2656: Exported external package typings file '/home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/node_modules/nativescript-telerik-ui/listview/listview.d.ts' is not a module. Please contact the package author to update the package definition.
app/examples/listview/layouts/listview-layouts.ts(17,46): error TS2339: Property 'os' does not exist on type 'typeof android'.
app/examples/listview/layouts/listview-layouts.ts(19,38): error TS2339: Property 'WindowManager' does not exist on type 'typeof view'.
app/examples/listview/layouts/listview-layouts.ts(24,46): error TS2339: Property 'os' does not exist on type 'typeof android'.
app/examples/listview/layouts/listview-layouts.ts(26,40): error TS2339: Property 'WindowManager' does not exist on type 'typeof view'.
app/examples/listview/reorder/listview-reorder-model.ts(42,9): error TS1095: A 'set' accessor cannot have a return type annotation.
app/examples/listview/reorder/listview-reorder.ts(2,33): error TS2306: File '/home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/node_modules/nativescript-telerik-ui/listview/listview.d.ts' is not a module.
app/examples/listview/reorder/listview-reorder.ts(2,33): error TS2656: Exported external package typings file '/home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/node_modules/nativescript-telerik-ui/listview/listview.d.ts' is not a module. Please contact the package author to update the package definition.
app/examples/listview/reorder/listview-reorder.ts(25,21): error TS2339: Property 'os' does not exist on type 'typeof android'.
app/examples/listview/reorder/listview-reorder.ts(26,44): error TS2339: Property 'WindowManager' does not exist on type 'typeof view'.
app/examples/listview/reorder/listview-reorder.ts(30,21): error TS2339: Property 'os' does not exist on type 'typeof android'.
app/examples/listview/reorder/listview-reorder.ts(31,42): error TS2339: Property 'WindowManager' does not exist on type 'typeof view'.
app/examples/listview/reorder/listview-reorder.ts(32,55): error TS2339: Property 'Color' does not exist on type 'typeof graphics'.
app/examples/listview/reorder/listview-reorder.ts(45,21): error TS2339: Property 'os' does not exist on type 'typeof android'.
app/examples/listview/reorder/listview-reorder.ts(46,42): error TS2339: Property 'WindowManager' does not exist on type 'typeof view'.
app/examples/listview/reorder/listview-reorder.ts(49,21): error TS2339: Property 'os' does not exist on type 'typeof android'.
app/examples/listview/reorder/listview-reorder.ts(50,44): error TS2339: Property 'WindowManager' does not exist on type 'typeof view'.
app/examples/listview/selection/detail-page.ts(7,24): error TS2307: Cannot find module 'Page'.
app/examples/listview/selection/main-page-model.ts(3,27): error TS2306: File '/home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/node_modules/nativescript-telerik-ui/listview/listview.d.ts' is not a module.
app/examples/listview/selection/main-page-model.ts(3,27): error TS2656: Exported external package typings file '/home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/node_modules/nativescript-telerik-ui/listview/listview.d.ts' is not a module. Please contact the package author to update the package definition.
app/examples/listview/selection/main-page-model.ts(211,37): error TS2339: Property 'items' does not exist on type 'View'.
app/examples/listview/selection/main-page-model.ts(246,22): error TS2339: Property 'notifySwipeToExecuteFinished' does not exist on type 'View'.
app/examples/listview/selection/main-page-model.ts(279,48): error TS2339: Property 'getSelectedItems' does not exist on type 'View'.
app/examples/listview/selection/main-page-model.ts(286,44): error TS2339: Property 'getSelectedItems' does not exist on type 'View'.
app/examples/listview/selection/main-page-model.ts(302,38): error TS2339: Property 'getSelectedItems' does not exist on type 'View'.
app/examples/listview/selection/main-page-model.ts(315,50): error TS2339: Property 'getSelectedItems' does not exist on type 'View'.
app/examples/listview/selection/main-page-model.ts(324,30): error TS2339: Property 'deselectItemAt' does not exist on type 'View'.
app/examples/listview/selection/main-page-model.ts(324,54): error TS2339: Property 'items' does not exist on type 'View'.
app/examples/listview/selection/main-page-model.ts(339,38): error TS2339: Property 'getSelectedItems' does not exist on type 'View'.
app/examples/listview/selection/main-page.ts(3,27): error TS2306: File '/home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/node_modules/nativescript-telerik-ui/listview/listview.d.ts' is not a module.
app/examples/listview/selection/main-page.ts(3,27): error TS2656: Exported external package typings file '/home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/node_modules/nativescript-telerik-ui/listview/listview.d.ts' is not a module. Please contact the package author to update the package definition.
Project successfully prepared

:config phase:  createDefaultIncludeFiles
        +found plugins: fresco
        +found plugins: nativescript-telerik-analytics

:config phase:  createPluginsConfigFile
        +creating product flavors include.gradle file in configurations folder...

:config phase:  pluginExtend
        +applying configuration from: /home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/platforms/android/configurations/fresco/include.gradle
        +applying configuration from: /home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/platforms/android/configurations/nativescript-telerik-analytics/include.gradle
        +applying configuration from: /home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/platforms/android/configurations/include.gradle

:config phase:  copyAarDependencies

:config phase:  addAarDependencies
        +adding dependency: /home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/platforms/android/libs/aar/widgets-release.aar
        +adding dependency: /home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/platforms/android/libs/aar/Chart-2015.3.1307-trial-release.aar
        +adding dependency: /home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/platforms/android/libs/aar/Common-2015.3.1307-trial-release.aar
        +adding dependency: /home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/platforms/android/libs/aar/Data-2015.3.1307-trial-release.aar
        +adding dependency: /home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/platforms/android/libs/aar/Input-2015.3.1307-trial-release.aar
        +adding dependency: /home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/platforms/android/libs/aar/List-2015.3.1307-trial-release.aar
        +adding dependency: /home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/platforms/android/libs/aar/Primitives-2015.3.1307-trial-release.aar
:preBuild UP-TO-DATE
:preNativescript-frescoNativescript-telerik-analyticsDebugBuild UP-TO-DATE
:checkNativescript-frescoNativescript-telerik-analyticsDebugManifest
:preNativescript-frescoNativescript-telerik-analyticsReleaseBuild UP-TO-DATE
:prepareChart201531307TrialReleaseLibrary UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2321Library
:prepareComAndroidSupportAppcompatV72321Library
:prepareComAndroidSupportSupportV42321Library
:prepareComAndroidSupportSupportVectorDrawable2321Library
:prepareComFacebookFrescoDrawee070Library UP-TO-DATE
:prepareComFacebookFrescoFbcore070Library UP-TO-DATE
:prepareComFacebookFrescoFresco070Library UP-TO-DATE
:prepareComFacebookFrescoImagepipeline070Library UP-TO-DATE
:prepareCommon201531307TrialReleaseLibrary UP-TO-DATE
:prepareData201531307TrialReleaseLibrary UP-TO-DATE
:prepareInput201531307TrialReleaseLibrary UP-TO-DATE
:prepareList201531307TrialReleaseLibrary UP-TO-DATE
:preparePrimitives201531307TrialReleaseLibrary UP-TO-DATE
:prepareWidgetsReleaseLibrary UP-TO-DATE
:prepareNativescript-frescoNativescript-telerik-analyticsDebugDependencies
:compileNativescript-frescoNativescript-telerik-analyticsDebugAidl
:compileNativescript-frescoNativescript-telerik-analyticsDebugRenderscript
:generateNativescript-frescoNativescript-telerik-analyticsDebugBuildConfig UP-TO-DATE
:cleanLocalAarFiles
:deleteJavaDir UP-TO-DATE
:ensureMetadataOutDir UP-TO-DATE
:collectAllJars
:isMetadataGenerationNecessary
:buildMetadata
Exception in thread "main" java.lang.IllegalArgumentException: Class android.support.v7.widget.AppCompatCheckedTextView conflict: /home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/platforms/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/23.2.1/jars/classes.jar and /home/mbernhardt/Development/Projects/NativeScript/nativescript-marketplace-demo/platforms/android/build/intermediates/exploded-aar/com.android.support/appcompat-v7/22.2.1/jars/classes.jar
        at com.telerik.metadata.ClassRepo.cacheJarFile(ClassRepo.java:21)
        at com.telerik.metadata.Builder.build(Builder.java:38)
        at com.telerik.metadata.Generator.main(Generator.java:44)
:buildMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildMetadata'.
> Process 'command '/usr/lib64/jvm/jdk1.8.0_73/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by prodigy7** [comment]
Okay, tried it again and now it works! Thank you for your support!
