### ISSUE TITLE
Program failed to link at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender

### ISSUE THREAD

**Issue by j99ht** [Yermo/nativescript-mapbox#87]
I cannot run mapbox plugin neither on my Android emulator, running Android 6 nor on a device with Android 4.2

However it runs on another device with Android 6.

The error I'm getting is the following 

`An uncaught Exception occurred on "main" thread.
java.lang.Error: program failed to link
at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:175)
at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:445)
at android.view.View.draw(View.java:14603)
at android.widget.FrameLayout.draw(FrameLayout.java:467)
at android.view.View.getDisplayList(View.java:13538)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.getDisplayList(View.java:13536)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.getDisplayList(View.java:13536)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.getDisplayList(View.java:13536)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.getDisplayList(View.java:13536)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.getDisplayList(View.java:13536)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.draw(View.java:14606)
at android.view.View.getDisplayList(View.java:13538)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.getDisplayList(View.java:13536)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.draw(View.java:14606)
at android.widget.FrameLayout.draw(FrameLayout.java:467)
at android.view.View.getDisplayList(View.java:13538)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.getDisplayList(View.java:13536)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.draw(View.java:14606)
at android.widget.FrameLayout.draw(FrameLayout.java:467)
at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2595)
at android.view.View.getDisplayList(View.java:13538)
at android.view.View.getDisplayList(View.java:13582)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1198)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2506)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2372)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2175)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1237)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5162)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
at android.view.Choreographer.doCallbacks(Choreographer.java:591)
at android.view.Choreographer.doFrame(Choreographer.java:561)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
at android.os.Handler.handleCallback(Handler.java:725)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:5317)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
at dalvik.system.NativeStart.main(Native Method)`

They way I'm including the map is the following

`<StackLayout>
<ContentView>
                <map:Mapbox xmlns:map="nativescript-mapbox"                      accessToken="mytoken"
                            mapStyle="mapbox://mymap"
                            latitude="50.88255"
                            longitude="4.44013"
                            zoomLevel="20"
                            showUserLocation="true"
                            hideLogo="true"
                            mapReady="onMapReady">
                </map:Mapbox>
            </ContentView>
        </StackLayout>`

Am I doing anything wrong?

**Comment by shyandsy** [comment]
exactly same problem

**Comment by EddyVerbruggen** [comment]
@shyandsy on what devices?

**Comment by shyandsy** [comment]
on android virtual machine api 24

@EddyVerbruggen 
https://github.com/EddyVerbruggen/nativescript-mapbox/issues/90

发自我的 iPhone

**Comment by EddyVerbruggen** [comment]
I hope this is fine with 2.5.2. Please reopen if the problem persists with a real device.

**Comment by seros00** [comment]
After updating to nativescript-mapbox 2.5.2, same problem in Android 4.2.2 device and emulator API 23.
The error with v2.5.2;

`An uncaught Exception occurred on "main" thread.
java.lang.Error: program failed to link
at com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender(Native Method)
at com.mapbox.mapboxsdk.maps.NativeMapView.render(NativeMapView.java:175)
at com.mapbox.mapboxsdk.maps.MapView.onDraw(MapView.java:444)
at android.view.View.draw(View.java:14603)
at android.widget.FrameLayout.draw(FrameLayout.java:467)
at android.view.View.getDisplayList(View.java:13538)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.getDisplayList(View.java:13536)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.getDisplayList(View.java:13536)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.getDisplayList(View.java:13536)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.getDisplayList(View.java:13536)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.getDisplayList(View.java:13536)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.draw(View.java:14606)
at android.view.View.getDisplayList(View.java:13538)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.getDisplayList(View.java:13536)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.draw(View.java:14606)
at android.widget.FrameLayout.draw(FrameLayout.java:467)
at android.view.View.getDisplayList(View.java:13538)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.getDisplayList(View.java:13536)
at android.view.View.getDisplayList(View.java:13582)
at android.view.View.draw(View.java:14316)
at android.view.ViewGroup.drawChild(ViewGroup.java:3155)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3024)
at android.view.View.draw(View.java:14606)
at android.widget.FrameLayout.draw(FrameLayout.java:467)
at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2595)
at android.view.View.getDisplayList(View.java:13538)
at android.view.View.getDisplayList(View.java:13582)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1198)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2506)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2372)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2175)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1237)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5162)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
at android.view.Choreographer.doCallbacks(Choreographer.java:591)
at android.view.Choreographer.doFrame(Choreographer.java:561)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
at android.os.Handler.handleCallback(Handler.java:725)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:5317)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
at dalvik.system.NativeStart.main(Native Method) `

**Comment by giperwlad** [comment]
Hi @EddyVerbruggen, 
Problem persists with a real device. http://crashes.to/s/7035cd80c4c
Mapbox versions:
mapbox-android-sdk:5.1.2
android-plugin-locationlayer:0.2.0-SNAPSHOT'

**Comment by j05u3** [comment]
Hi, using mapbox 5.1.4 here and also receiving similar stack traces (28 on the last week):

Exception java.lang.Error: program failed to link:
`com.mapbox.mapboxsdk.maps.NativeMapView.nativeRender (NativeMapView.java)
com.mapbox.mapboxsdk.maps.NativeMapView.render (NativeMapView.java:179)
com.mapbox.mapboxsdk.maps.MapView.onDraw (MapView.java:407)
android.view.View.draw (View.java:14600)
android.widget.FrameLayout.draw (FrameLayout.java:467)
android.view.View.getDisplayList (View.java:13535)
android.view.View.getDisplayList (View.java:13579)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3137)
android.view.View.getDisplayList (View.java:13472)
android.view.View.getDisplayList (View.java:13579)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3137)
android.view.View.getDisplayList (View.java:13472)
android.view.View.getDisplayList (View.java:13579)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3137)
android.view.View.getDisplayList (View.java:13472)
android.view.View.getDisplayList (View.java:13579)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3137)
android.view.View.getDisplayList (View.java:13472)
android.view.View.getDisplayList (View.java:13579)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3137)
android.view.View.getDisplayList (View.java:13472)
android.view.View.getDisplayList (View.java:13579)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3137)
android.view.View.getDisplayList (View.java:13472)
android.view.View.getDisplayList (View.java:13579)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3137)
android.view.View.getDisplayList (View.java:13472)
android.view.View.getDisplayList (View.java:13579)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3137)
android.view.View.getDisplayList (View.java:13472)
android.view.View.getDisplayList (View.java:13579)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3137)
android.view.View.getDisplayList (View.java:13472)
android.view.View.getDisplayList (View.java:13579)
android.view.ViewGroup.dispatchGetDisplayList (ViewGroup.java:3137)
android.view.View.getDisplayList (View.java:13472)
android.view.View.getDisplayList (View.java:13579)
android.view.HardwareRenderer$GlRenderer.draw (HardwareRenderer.java:1198)
android.view.ViewRootImpl.draw (ViewRootImpl.java:2506)
android.view.ViewRootImpl.performDraw (ViewRootImpl.java:2372)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2175)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1237)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:5181)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:791)
android.view.Choreographer.doCallbacks (Choreographer.java:591)
android.view.Choreographer.doFrame (Choreographer.java:561)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:777)
android.os.Handler.handleCallback (Handler.java:725)
android.os.Handler.dispatchMessage (Handler.java:92)
android.os.Looper.loop (Looper.java:176)
android.app.ActivityThread.main (ActivityThread.java:5299)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:511)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1102)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:869)
dalvik.system.NativeStart.main (NativeStart.java)`
