### ISSUE TITLE
getZoomLevel is not a function

### ISSUE THREAD

**Issue by j99ht** [Yermo/nativescript-mapbox#92]
I'm trying to use getZoomLevel as in the mapbox demo

```
map.getZoomLevel().then(
            function(result) {
                dialogs.alert({
                    title: "Zoom Level",
                    message: JSON.stringify(result),
                    okButtonText: "OK"
                });
            },
            function(error) {
                console.log("mapbox getCenter error: " + error);
            }
        );
```
However, I'm getting this error

```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onMapClick failed

TypeError: map.getZoomLevel is not a function
File: "file:///data/data/org.nativescript.ctdemo/files/app/views/map/map.js, line: 61, column: 19

StackTrace: 
	Frame: function:'', file:'file:///data/data/org.nativescript.ctdemo/files/app/views/map/map.js', line: 61, column: 20
	Frame: function:'onMapClick', file:'file:///data/data/org.nativescript.ctdemo/files/app/tns_modules/nativescript-mapbox/mapbox.js', line: 842, column: 15


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1197)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1061)
	at com.tns.Runtime.callJSMethod(Runtime.java:1047)
	at com.tns.Runtime.callJSMethod(Runtime.java:1028)
	at com.tns.Runtime.callJSMethod(Runtime.java:1018)
	at com.tns.gen.com.mapbox.mapboxsdk.maps.MapboxMap_OnMapClickListener.onMapClick(com.mapbox.mapboxsdk.maps.MapboxMap$OnMapClickListener.java)
	at com.mapbox.mapboxsdk.maps.MapGestureDetector$GestureListener.onSingleTapConfirmed(MapGestureDetector.java:300)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5551)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

```
I'm using mapbox plugin 2.5.1 and tried also with 2.5.2 (but the map was not stable with this release). And nativescript 2.5.2

Am I doing anything wrong?

**Comment by seros00** [comment]
I have the same issue with a XML-based map. With `mapbox.show()` the `getZoomLevel()` function works fine.

I just read the `README.md` file and it says:

> Other methods you can invoke like this from an XML-declared map are: `removeMarkers`, `setCenter`, `setZoomLevel`, `setViewport`, `setTilt`, `setMapStyle`, `animateCamera`, `addPolygon`, `addPolyline`, `removePolylines `and `setOnMapClickListener`.

So, is it impossiple to get the zoom level in a XML-based map?

**Comment by seros00** [comment]
I have create 3 (sorry!) pull requests to fix this.
Once the code is adapted for XML-based maps, the returned value could not be obtained because the functions in the prototype were not 'thenables'.
This way, you can add more `getX() `functions.

**Comment by EddyVerbruggen** [comment]
Thanks for your PR's @seros00, merged them all and will release a new version shortly.
